<?php

namespace AppBundle\Repository;

/**
 * CheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckoutRepository extends \Doctrine\ORM\EntityRepository
{
}
