<?php

namespace AppBundle\Repository;

/**
 * LineItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineItemRepository extends \Doctrine\ORM\EntityRepository
{
}
