<?php

namespace AppBundle\Repository;

/**
 * PosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;

class PosterRepository extends \Doctrine\ORM\EntityRepository {

    public function getPosterWithMovie($query) {
        $qb = $this->createQueryBuilder('p');
        $qb
                ->innerJoin('p.movie', 'm')
                ->where('m.director = :query')
                ->setParameter('query', $query)
        ;
       /* $qb
                ->innerJoin('p.movie', 'm')
                ->addSelect('m')
        ;
        $qb->where($qb->expr()->in('m.title = :lol'));
        * ;*/
        
        return $qb
                        ->getQuery() 
                        ->getResult();
        
    }

}
